version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Berlin"
    target-branch: "main"
    commit-message:
      prefix: "maven dependency"
    labels:
      - "dependency"
