name: Deploy to Sonatype

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Import GPG Key
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg  # Secure permissions
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private-key.asc
          gpg --batch --import private-key.asc
          rm private-key.asc
          echo "use-agent" > ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          chmod 600 ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
          chmod 600 ~/.gnupg/gpg-agent.conf
          gpgconf --reload gpg-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Verify GPG key
        run: |
          gpg --list-secret-keys --keyid-format LONG
          gpg --fingerprint
          gpg --list-keys

      - name: Debug Environment Variables
        run: env | grep SONATYPE

      - name: Build and Deploy
        run: mvn clean deploy -s ~/.m2/settings.xml -P release -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -X --batch-mode
        env:
          GPG_TTY: $(tty)
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}